// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: gRPCService.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981
#region Designer generated code

using grpc = global::Grpc.Core;

namespace gRPCDefinition {
  public static partial class gRPCService
  {
    static readonly string __ServiceName = "gRPCServiceDefinition.gRPCService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::gRPCDefinition.CommandRequest> __Marshaller_gRPCServiceDefinition_CommandRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::gRPCDefinition.CommandRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::gRPCDefinition.CommandResponce> __Marshaller_gRPCServiceDefinition_CommandResponce = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::gRPCDefinition.CommandResponce.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::gRPCDefinition.NullMessage> __Marshaller_gRPCServiceDefinition_NullMessage = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::gRPCDefinition.NullMessage.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::gRPCDefinition.CommandRequest, global::gRPCDefinition.CommandResponce> __Method_CommandStream = new grpc::Method<global::gRPCDefinition.CommandRequest, global::gRPCDefinition.CommandResponce>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "CommandStream",
        __Marshaller_gRPCServiceDefinition_CommandRequest,
        __Marshaller_gRPCServiceDefinition_CommandResponce);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::gRPCDefinition.NullMessage, global::gRPCDefinition.NullMessage> __Method_CheckStreamRemoved = new grpc::Method<global::gRPCDefinition.NullMessage, global::gRPCDefinition.NullMessage>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "CheckStreamRemoved",
        __Marshaller_gRPCServiceDefinition_NullMessage,
        __Marshaller_gRPCServiceDefinition_NullMessage);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::gRPCDefinition.NullMessage, global::gRPCDefinition.NullMessage> __Method_CheckConection = new grpc::Method<global::gRPCDefinition.NullMessage, global::gRPCDefinition.NullMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CheckConection",
        __Marshaller_gRPCServiceDefinition_NullMessage,
        __Marshaller_gRPCServiceDefinition_NullMessage);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::gRPCDefinition.GRPCServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of gRPCService</summary>
    [grpc::BindServiceMethod(typeof(gRPCService), "BindService")]
    public abstract partial class gRPCServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task CommandStream(grpc::IAsyncStreamReader<global::gRPCDefinition.CommandRequest> requestStream, grpc::IServerStreamWriter<global::gRPCDefinition.CommandResponce> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::gRPCDefinition.NullMessage> CheckStreamRemoved(grpc::IAsyncStreamReader<global::gRPCDefinition.NullMessage> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::gRPCDefinition.NullMessage> CheckConection(global::gRPCDefinition.NullMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(gRPCServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CommandStream, serviceImpl.CommandStream)
          .AddMethod(__Method_CheckStreamRemoved, serviceImpl.CheckStreamRemoved)
          .AddMethod(__Method_CheckConection, serviceImpl.CheckConection).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, gRPCServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CommandStream, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::gRPCDefinition.CommandRequest, global::gRPCDefinition.CommandResponce>(serviceImpl.CommandStream));
      serviceBinder.AddMethod(__Method_CheckStreamRemoved, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::gRPCDefinition.NullMessage, global::gRPCDefinition.NullMessage>(serviceImpl.CheckStreamRemoved));
      serviceBinder.AddMethod(__Method_CheckConection, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::gRPCDefinition.NullMessage, global::gRPCDefinition.NullMessage>(serviceImpl.CheckConection));
    }

  }
}
#endregion
